"""empty message

Revision ID: 883afdf98309
Revises: 6057d26e3194
Create Date: 2022-02-12 14:58:09.872656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883afdf98309'
down_revision = '6057d26e3194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
